gitlab:
  image: gitlab/gitlab-ce:${GITLAB_CE_VERSION}
  restart: always
  container_name: gitlab
  hostname: ${GITLAB_HOST}
  environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Australia/Sydney'
        gitlab_rails['gitlab_email_from'] = 'gitlab-no-reply@example.com'
        gitlab_rails['gitlab_email_display_name'] = 'GitLab Administrator'
        gitlab_rails['gitlab_email_reply_to'] = 'admin@hexample.com'
        gitlab_rails['smtp_enable'] = false
        gitlab_rails['smtp_address'] = "smtp.example.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "no-reply@example.com"
        gitlab_rails['smtp_password'] = "changeMeToSomethingGood"
        gitlab_rails['smtp_domain'] = "example.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
  ports:
    - "80:80"
    - "443:443"
    - "22:22"
  volumes:
    - ./data/gitlab/config:/etc/gitlab:rw
    - ./data/gitlab/logs:/var/log/gitlab:rw
    - ./data/gitlab/data:/var/opt/gitlab:rw

